### ISSUE TITLE
Contextual menu hidden in the last line of a grid

### ISSUE THREAD

**Issue by padiazg** [TykTechnologies/raava-admin#6]
With the new Tyk styling, some actions are hidden by the frame.

Here we can see the contextual menu at the three dots on the right
![Captura de pantalla de 2021-06-22 15-22-18](https://user-images.githubusercontent.com/15754252/122987103-3987da80-d36e-11eb-810c-e6aef3748755.png)
Here at the last line, this contextual menú is hidden below the frame
![Captura de pantalla de 2021-06-22 15-22-31](https://user-images.githubusercontent.com/15754252/122987114-3d1b6180-d36e-11eb-8a6d-e9507053ffcf.png)

**Comment by ConsM** [comment]
Closing. Was addressed at https://github.com/TykTechnologies/raava-admin/pull/7
